### ISSUE TITLE
[4.x] BoltRoutingNeo4jDriver does not support `neo4j+s` and `neo4j+ssc`

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#248]
This is from a Liquigraph example, using Hikari pool:
```java
Caused by: java.lang.RuntimeException: Driver org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver claims to not accept jdbcUrl, jdbc:neo4j:neo4j+s://HOST
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:325) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[HikariCP-3.4.5.jar:na]
```

Same happens with `neo4j+ssc`.

I need to double check, but I think the `trust.strategy*` and `encryption` need to be **not** used when using any of the `neo4j` scheme.

**Comment by fbiville** [comment]
Fixed by https://github.com/neo4j-contrib/neo4j-jdbc/commit/255a55f3dfac15bca06cc172173a372081e1f534

**Comment by paolodedo** [comment]
Hello, tried with release 4.0.2 but still not working...

Here's pom (only neo4j part, spring boot parent is 2.4.1):

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
</dependency>
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-jdbc-driver</artifactId>
    <version>4.0.2</version>
</dependency>
<dependency>
    <groupId>org.liquigraph</groupId>
    <artifactId>liquigraph-spring-boot-starter</artifactId>
    <version>4.0.3</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-neo4j</artifactId>
</dependency>
```

Here's config: 

```
spring:
  datasource: 
    url: jdbc:neo4j:neo4j+s://neo4j-instance.com
    driver-class-name: org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver
    username: neo4j
    password: psw
```

Here's output:

`java.sql.SQLException: java.lang.IllegalArgumentException: Illegal URI scheme, expected 'neo4j' in 'neo4j+s://neo4j-instance.com'
`

Could you please explain me how to make it work?

Thanks 💯
